version: "3.2"
services:
  nginx:
    depends_on:
      - tileserver
    environment:
      - NGINX_PORT=${NGINX_PORT:-3000}
      - NODE_ENV=development
    image: 'nginx:latest'
    networks:
      - tilenet
    ports:
      - ${NGINX_PORT:-3000}:80
    volumes:
      - ./nginx:/etc/nginx
      - ./map/:/map

  tilebuilder:
    build:
      context: ./tilebuilder
    image: terrastories/tilebuilder
    network_mode: none
    volumes:
      - type: bind
        source: ./tilebuilder/script
        target: /script
      - type: bind
        source: mbtiles
        target: /data/mbtiles
      - type: bind
        source: ./tilebuilder/shapefiles
        target: /data/shapefiles

  tileserver:
    image: klokantech/tileserver-gl
    networks:
      - tilenet
    volumes:
      - type: bind
        source: ./tileserver/data
        target: /data
      - type: bind
        source: mbtiles
        target: /data/mbtiles

networks:
  tilenet:

volumes:
  mbtiles: